title: "Tue's blog"
email: lkmtue@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lkmtue.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lkmtue
github_username:  lkmtue
linkedin_username: lkmtue

markdown: kramdown
plugins:
  - jekyll-feed

